language: node_js
node_js:
- node
services:
- postgresql
notifications:
  email: false
cache:
  yarn: true
  directories:
  - node_modules
before_install:
# - openssl aes-256-cbc -K $encrypted_a670f47ecb3a_key -iv $encrypted_a670f47ecb3a_iv
#   -in .travis/deploy.key.enc -out .travis/deploy.key -d
- psql -c 'create database sources;' -U postgres
- psql -c 'create database "sources-test";' -U postgres

script:
- npm install codecov -g
- yarn test --coverage
after_success:
- codecov
- chmod +x .travis/deploy.sh
- .travis/deploy.sh
