language: node_js
node_js:
- node
notifications:
  email: false
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_a670f47ecb3a_key -iv $encrypted_a670f47ecb3a_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
script:
- npm install codecov -g
- yarn build
- yarn test --coverage
after_success:
- codecov
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan 192.241.198.54 >> ~/.ssh/known_hosts
- git remote add deploy dokku@192.241.198.54:uclaradio-api
- git config --global push.default simple
- git push deploy master
