language: node_js
node_js:
  - node
notifications:
  email: false
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm install codecov -g
  - yarn build
  - yarn test --coverage
after_success:
  - codecov
